language: node_js

services:
    - xvfb

env:
    global:
        - MOZ_HEADLESS=1
        - CI=false

addons:
    firefox: latest

node_js:
    - 'node'
    - 'lts/*'

sudo: true

git:
    submodules: false

install:
    - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz -P ~/
    - tar -xzf ~/geckodriver-v0.27.0-linux64.tar.gz -C ~/
    - rm ~/geckodriver-v0.27.0-linux64.tar.gz
    - sudo mv -f ~/geckodriver /usr/local/share
    - sudo chmod +x /usr/local/share/geckodriver
    - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver

before_script:
    - npm install
    - npm i selenium-webdriver@3.6.0
    - npm run build:prod
    - '/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16'
    - npm run serve &
    - sleep 3

script:
    - npm test
# after_success:
#     - npm run lint
